name: Build, lint, test, package and publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9 ]
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

      - name: Determine version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            version="${GITHUB_REF##*/}"
          else
            version="0.dev${{ github.run_id }}"
          fi

          echo "Setting version to $version"
          echo "::set-output name=version::$version"

      - name: lint, test, build, package
        run: |
          docker build . \
            --tag ${{ github.repository }}/build:latest \
            --build-arg python_version=${{ matrix.python-version }} \
            --build-arg clin_version=${{ steps.get_version.outputs.version }} \
            --label org.opencontainers.image.version=${{ steps.get_version.outputs.version  }} \
            --label org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }} \
            --label org.opencontainers.image.revision=${{ github.sha }} \
            --label org.opencontainers.image.ref.name=${{ github.ref }} \
            --target build

      - name: Publish to PyPI
        if: github.event_name == 'release' && matrix.python-version == '3.7'
        run: |
          docker run --rm clin-build publish \
            -e POETRY_PYPI_TOKEN_PYPI=${{ secrets.PYPI_TOKEN }}

      - name: Build and push CLI Docker image
        if: matrix.python-version == '3.9'
        run: |
          docker build . \
            --tag ghcr.io/${{ github.repository }}/cli:latest \
            --tag ghcr.io/${{ github.repository }}/cli:${{ steps.get_version.outputs.version }} \
            --build-arg python_version=${{ matrix.python-version }} \
            --build-arg clin_version=${{ steps.get_version.outputs.version }} \
            --label org.opencontainers.image.version=${{ steps.get_version.outputs.version  }} \
            --label org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }} \
            --label org.opencontainers.image.revision=${{ github.sha }} \
            --label org.opencontainers.image.ref.name=${{ github.ref }} \
            --target cli

          docker push --all-tags ghcr.io/${{ github.repository }}/cli
